//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPerformancePredictionTool_CW1.StudySessionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudySessionModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StudySessionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime DateField;
        
        private double HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudySessionService.StudySessionSoap")]
    public interface StudySessionSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudySessions", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsResponse GetStudySessions(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudySessions", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsResponse> GetStudySessionsAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudySessionById", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdResponse GetStudySessionById(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudySessionById", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdResponse> GetStudySessionByIdAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudySession", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionResponse AddStudySession(StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudySession", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionResponse> AddStudySessionAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudySession", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionResponse UpdateStudySession(StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudySession", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionResponse> UpdateStudySessionAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStudySession", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionResponse DeleteStudySession(StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStudySession", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionResponse> DeleteStudySessionAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudySessionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudySessions", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequestBody Body;
        
        public GetStudySessionsRequest() {
        }
        
        public GetStudySessionsRequest(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudySessionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetStudySessionsRequestBody() {
        }
        
        public GetStudySessionsRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudySessionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudySessionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsResponseBody Body;
        
        public GetStudySessionsResponse() {
        }
        
        public GetStudySessionsResponse(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudySessionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionModel[] GetStudySessionsResult;
        
        public GetStudySessionsResponseBody() {
        }
        
        public GetStudySessionsResponseBody(StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionModel[] GetStudySessionsResult) {
            this.GetStudySessionsResult = GetStudySessionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudySessionByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudySessionById", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequestBody Body;
        
        public GetStudySessionByIdRequest() {
        }
        
        public GetStudySessionByIdRequest(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudySessionByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sessionId;
        
        public GetStudySessionByIdRequestBody() {
        }
        
        public GetStudySessionByIdRequestBody(string userName, int sessionId) {
            this.userName = userName;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudySessionByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudySessionByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdResponseBody Body;
        
        public GetStudySessionByIdResponse() {
        }
        
        public GetStudySessionByIdResponse(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudySessionByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionModel GetStudySessionByIdResult;
        
        public GetStudySessionByIdResponseBody() {
        }
        
        public GetStudySessionByIdResponseBody(StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionModel GetStudySessionByIdResult) {
            this.GetStudySessionByIdResult = GetStudySessionByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStudySessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStudySession", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequestBody Body;
        
        public AddStudySessionRequest() {
        }
        
        public AddStudySessionRequest(StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStudySessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double hours;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subject;
        
        public AddStudySessionRequestBody() {
        }
        
        public AddStudySessionRequestBody(string userName, System.DateTime date, double hours, string subject) {
            this.userName = userName;
            this.date = date;
            this.hours = hours;
            this.subject = subject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStudySessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStudySessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionResponseBody Body;
        
        public AddStudySessionResponse() {
        }
        
        public AddStudySessionResponse(StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStudySessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddStudySessionResult;
        
        public AddStudySessionResponseBody() {
        }
        
        public AddStudySessionResponseBody(string AddStudySessionResult) {
            this.AddStudySessionResult = AddStudySessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudySessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudySession", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequestBody Body;
        
        public UpdateStudySessionRequest() {
        }
        
        public UpdateStudySessionRequest(StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudySessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double hours;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subject;
        
        public UpdateStudySessionRequestBody() {
        }
        
        public UpdateStudySessionRequestBody(string userName, int sessionId, System.DateTime date, double hours, string subject) {
            this.userName = userName;
            this.sessionId = sessionId;
            this.date = date;
            this.hours = hours;
            this.subject = subject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudySessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudySessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionResponseBody Body;
        
        public UpdateStudySessionResponse() {
        }
        
        public UpdateStudySessionResponse(StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudySessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateStudySessionResult;
        
        public UpdateStudySessionResponseBody() {
        }
        
        public UpdateStudySessionResponseBody(string UpdateStudySessionResult) {
            this.UpdateStudySessionResult = UpdateStudySessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteStudySessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteStudySession", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequestBody Body;
        
        public DeleteStudySessionRequest() {
        }
        
        public DeleteStudySessionRequest(StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteStudySessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sessionId;
        
        public DeleteStudySessionRequestBody() {
        }
        
        public DeleteStudySessionRequestBody(string userName, int sessionId) {
            this.userName = userName;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteStudySessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteStudySessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionResponseBody Body;
        
        public DeleteStudySessionResponse() {
        }
        
        public DeleteStudySessionResponse(StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteStudySessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteStudySessionResult;
        
        public DeleteStudySessionResponseBody() {
        }
        
        public DeleteStudySessionResponseBody(string DeleteStudySessionResult) {
            this.DeleteStudySessionResult = DeleteStudySessionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudySessionSoapChannel : StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudySessionSoapClient : System.ServiceModel.ClientBase<StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap>, StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap {
        
        public StudySessionSoapClient() {
        }
        
        public StudySessionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudySessionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudySessionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudySessionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsResponse StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.GetStudySessions(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequest request) {
            return base.Channel.GetStudySessions(request);
        }
        
        public StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionModel[] GetStudySessions(string userName) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequestBody();
            inValue.Body.userName = userName;
            StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsResponse retVal = ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).GetStudySessions(inValue);
            return retVal.Body.GetStudySessionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsResponse> StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.GetStudySessionsAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequest request) {
            return base.Channel.GetStudySessionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsResponse> GetStudySessionsAsync(string userName) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionsRequestBody();
            inValue.Body.userName = userName;
            return ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).GetStudySessionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdResponse StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.GetStudySessionById(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequest request) {
            return base.Channel.GetStudySessionById(request);
        }
        
        public StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionModel GetStudySessionById(string userName, int sessionId) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdResponse retVal = ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).GetStudySessionById(inValue);
            return retVal.Body.GetStudySessionByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdResponse> StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.GetStudySessionByIdAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequest request) {
            return base.Channel.GetStudySessionByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdResponse> GetStudySessionByIdAsync(string userName, int sessionId) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.GetStudySessionByIdRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            return ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).GetStudySessionByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionResponse StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.AddStudySession(StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequest request) {
            return base.Channel.AddStudySession(request);
        }
        
        public string AddStudySession(string userName, System.DateTime date, double hours, string subject) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.date = date;
            inValue.Body.hours = hours;
            inValue.Body.subject = subject;
            StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionResponse retVal = ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).AddStudySession(inValue);
            return retVal.Body.AddStudySessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionResponse> StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.AddStudySessionAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequest request) {
            return base.Channel.AddStudySessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionResponse> AddStudySessionAsync(string userName, System.DateTime date, double hours, string subject) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.AddStudySessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.date = date;
            inValue.Body.hours = hours;
            inValue.Body.subject = subject;
            return ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).AddStudySessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionResponse StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.UpdateStudySession(StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequest request) {
            return base.Channel.UpdateStudySession(request);
        }
        
        public string UpdateStudySession(string userName, int sessionId, System.DateTime date, double hours, string subject) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            inValue.Body.date = date;
            inValue.Body.hours = hours;
            inValue.Body.subject = subject;
            StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionResponse retVal = ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).UpdateStudySession(inValue);
            return retVal.Body.UpdateStudySessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionResponse> StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.UpdateStudySessionAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequest request) {
            return base.Channel.UpdateStudySessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionResponse> UpdateStudySessionAsync(string userName, int sessionId, System.DateTime date, double hours, string subject) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.UpdateStudySessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            inValue.Body.date = date;
            inValue.Body.hours = hours;
            inValue.Body.subject = subject;
            return ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).UpdateStudySessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionResponse StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.DeleteStudySession(StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequest request) {
            return base.Channel.DeleteStudySession(request);
        }
        
        public string DeleteStudySession(string userName, int sessionId) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionResponse retVal = ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).DeleteStudySession(inValue);
            return retVal.Body.DeleteStudySessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionResponse> StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap.DeleteStudySessionAsync(StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequest request) {
            return base.Channel.DeleteStudySessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionResponse> DeleteStudySessionAsync(string userName, int sessionId) {
            StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequest inValue = new StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.StudySessionService.DeleteStudySessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            return ((StudentsPerformancePredictionTool_CW1.StudySessionService.StudySessionSoap)(this)).DeleteStudySessionAsync(inValue);
        }
    }
}
