//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPerformancePredictionTool_CW1.ReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ReportModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private double StudyHoursField;
        
        private int StudySessionsField;
        
        private double BreakHoursField;
        
        private int BreakSessionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double StudyHours {
            get {
                return this.StudyHoursField;
            }
            set {
                if ((this.StudyHoursField.Equals(value) != true)) {
                    this.StudyHoursField = value;
                    this.RaisePropertyChanged("StudyHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StudySessions {
            get {
                return this.StudySessionsField;
            }
            set {
                if ((this.StudySessionsField.Equals(value) != true)) {
                    this.StudySessionsField = value;
                    this.RaisePropertyChanged("StudySessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double BreakHours {
            get {
                return this.BreakHoursField;
            }
            set {
                if ((this.BreakHoursField.Equals(value) != true)) {
                    this.BreakHoursField = value;
                    this.RaisePropertyChanged("BreakHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int BreakSessions {
            get {
                return this.BreakSessionsField;
            }
            set {
                if ((this.BreakSessionsField.Equals(value) != true)) {
                    this.BreakSessionsField = value;
                    this.RaisePropertyChanged("BreakSessions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.ReportSoap")]
    public interface ReportSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateReport", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportResponse GenerateReport(StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateReport", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportResponse> GenerateReportAsync(StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateReport", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequestBody Body;
        
        public GenerateReportRequest() {
        }
        
        public GenerateReportRequest(StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endDate;
        
        public GenerateReportRequestBody() {
        }
        
        public GenerateReportRequestBody(string userName, System.DateTime startDate, System.DateTime endDate) {
            this.userName = userName;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportResponseBody Body;
        
        public GenerateReportResponse() {
        }
        
        public GenerateReportResponse(StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentsPerformancePredictionTool_CW1.ReportService.ReportModel[] GenerateReportResult;
        
        public GenerateReportResponseBody() {
        }
        
        public GenerateReportResponseBody(StudentsPerformancePredictionTool_CW1.ReportService.ReportModel[] GenerateReportResult) {
            this.GenerateReportResult = GenerateReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportSoapChannel : StudentsPerformancePredictionTool_CW1.ReportService.ReportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportSoapClient : System.ServiceModel.ClientBase<StudentsPerformancePredictionTool_CW1.ReportService.ReportSoap>, StudentsPerformancePredictionTool_CW1.ReportService.ReportSoap {
        
        public ReportSoapClient() {
        }
        
        public ReportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportResponse StudentsPerformancePredictionTool_CW1.ReportService.ReportSoap.GenerateReport(StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequest request) {
            return base.Channel.GenerateReport(request);
        }
        
        public StudentsPerformancePredictionTool_CW1.ReportService.ReportModel[] GenerateReport(string userName, System.DateTime startDate, System.DateTime endDate) {
            StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequest inValue = new StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportResponse retVal = ((StudentsPerformancePredictionTool_CW1.ReportService.ReportSoap)(this)).GenerateReport(inValue);
            return retVal.Body.GenerateReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportResponse> StudentsPerformancePredictionTool_CW1.ReportService.ReportSoap.GenerateReportAsync(StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequest request) {
            return base.Channel.GenerateReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportResponse> GenerateReportAsync(string userName, System.DateTime startDate, System.DateTime endDate) {
            StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequest inValue = new StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.ReportService.GenerateReportRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            return ((StudentsPerformancePredictionTool_CW1.ReportService.ReportSoap)(this)).GenerateReportAsync(inValue);
        }
    }
}
