//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPerformancePredictionTool_CW1.PredictionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PredictionModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PredictionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        private double PredictedGradeField;
        
        private double HoursToPassField;
        
        private double HoursToDistinctionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double PredictedGrade {
            get {
                return this.PredictedGradeField;
            }
            set {
                if ((this.PredictedGradeField.Equals(value) != true)) {
                    this.PredictedGradeField = value;
                    this.RaisePropertyChanged("PredictedGrade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double HoursToPass {
            get {
                return this.HoursToPassField;
            }
            set {
                if ((this.HoursToPassField.Equals(value) != true)) {
                    this.HoursToPassField = value;
                    this.RaisePropertyChanged("HoursToPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double HoursToDistinction {
            get {
                return this.HoursToDistinctionField;
            }
            set {
                if ((this.HoursToDistinctionField.Equals(value) != true)) {
                    this.HoursToDistinctionField = value;
                    this.RaisePropertyChanged("HoursToDistinction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PredictionService.PredictionSoap")]
    public interface PredictionSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PredictGrades", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesResponse PredictGrades(StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PredictGrades", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesResponse> PredictGradesAsync(StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PredictGradesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PredictGrades", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequestBody Body;
        
        public PredictGradesRequest() {
        }
        
        public PredictGradesRequest(StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PredictGradesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public PredictGradesRequestBody() {
        }
        
        public PredictGradesRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PredictGradesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PredictGradesResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesResponseBody Body;
        
        public PredictGradesResponse() {
        }
        
        public PredictGradesResponse(StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PredictGradesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentsPerformancePredictionTool_CW1.PredictionService.PredictionModel[] PredictGradesResult;
        
        public PredictGradesResponseBody() {
        }
        
        public PredictGradesResponseBody(StudentsPerformancePredictionTool_CW1.PredictionService.PredictionModel[] PredictGradesResult) {
            this.PredictGradesResult = PredictGradesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PredictionSoapChannel : StudentsPerformancePredictionTool_CW1.PredictionService.PredictionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PredictionSoapClient : System.ServiceModel.ClientBase<StudentsPerformancePredictionTool_CW1.PredictionService.PredictionSoap>, StudentsPerformancePredictionTool_CW1.PredictionService.PredictionSoap {
        
        public PredictionSoapClient() {
        }
        
        public PredictionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PredictionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PredictionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PredictionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesResponse StudentsPerformancePredictionTool_CW1.PredictionService.PredictionSoap.PredictGrades(StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequest request) {
            return base.Channel.PredictGrades(request);
        }
        
        public StudentsPerformancePredictionTool_CW1.PredictionService.PredictionModel[] PredictGrades(string user) {
            StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequest inValue = new StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequestBody();
            inValue.Body.user = user;
            StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesResponse retVal = ((StudentsPerformancePredictionTool_CW1.PredictionService.PredictionSoap)(this)).PredictGrades(inValue);
            return retVal.Body.PredictGradesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesResponse> StudentsPerformancePredictionTool_CW1.PredictionService.PredictionSoap.PredictGradesAsync(StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequest request) {
            return base.Channel.PredictGradesAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesResponse> PredictGradesAsync(string user) {
            StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequest inValue = new StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.PredictionService.PredictGradesRequestBody();
            inValue.Body.user = user;
            return ((StudentsPerformancePredictionTool_CW1.PredictionService.PredictionSoap)(this)).PredictGradesAsync(inValue);
        }
    }
}
