//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPerformancePredictionTool_CW1.BreakSessionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BreakSessionModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BreakSessionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime DateField;
        
        private double HoursField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BreakSessionService.BreakSessionSoap")]
    public interface BreakSessionSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBreakSessions", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsResponse GetBreakSessions(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBreakSessions", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsResponse> GetBreakSessionsAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBreakSessionById", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdResponse GetBreakSessionById(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBreakSessionById", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdResponse> GetBreakSessionByIdAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBreakSession", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionResponse AddBreakSession(StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBreakSession", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionResponse> AddBreakSessionAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBreakSession", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionResponse UpdateBreakSession(StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBreakSession", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionResponse> UpdateBreakSessionAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBreakSession", ReplyAction="*")]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionResponse DeleteBreakSession(StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBreakSession", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionResponse> DeleteBreakSessionAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBreakSessionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBreakSessions", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequestBody Body;
        
        public GetBreakSessionsRequest() {
        }
        
        public GetBreakSessionsRequest(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBreakSessionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetBreakSessionsRequestBody() {
        }
        
        public GetBreakSessionsRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBreakSessionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBreakSessionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsResponseBody Body;
        
        public GetBreakSessionsResponse() {
        }
        
        public GetBreakSessionsResponse(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBreakSessionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionModel[] GetBreakSessionsResult;
        
        public GetBreakSessionsResponseBody() {
        }
        
        public GetBreakSessionsResponseBody(StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionModel[] GetBreakSessionsResult) {
            this.GetBreakSessionsResult = GetBreakSessionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBreakSessionByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBreakSessionById", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequestBody Body;
        
        public GetBreakSessionByIdRequest() {
        }
        
        public GetBreakSessionByIdRequest(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBreakSessionByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sessionId;
        
        public GetBreakSessionByIdRequestBody() {
        }
        
        public GetBreakSessionByIdRequestBody(string userName, int sessionId) {
            this.userName = userName;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBreakSessionByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBreakSessionByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdResponseBody Body;
        
        public GetBreakSessionByIdResponse() {
        }
        
        public GetBreakSessionByIdResponse(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBreakSessionByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionModel GetBreakSessionByIdResult;
        
        public GetBreakSessionByIdResponseBody() {
        }
        
        public GetBreakSessionByIdResponseBody(StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionModel GetBreakSessionByIdResult) {
            this.GetBreakSessionByIdResult = GetBreakSessionByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBreakSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBreakSession", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequestBody Body;
        
        public AddBreakSessionRequest() {
        }
        
        public AddBreakSessionRequest(StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBreakSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double hours;
        
        public AddBreakSessionRequestBody() {
        }
        
        public AddBreakSessionRequestBody(string userName, System.DateTime date, double hours) {
            this.userName = userName;
            this.date = date;
            this.hours = hours;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBreakSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBreakSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionResponseBody Body;
        
        public AddBreakSessionResponse() {
        }
        
        public AddBreakSessionResponse(StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBreakSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddBreakSessionResult;
        
        public AddBreakSessionResponseBody() {
        }
        
        public AddBreakSessionResponseBody(string AddBreakSessionResult) {
            this.AddBreakSessionResult = AddBreakSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBreakSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBreakSession", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequestBody Body;
        
        public UpdateBreakSessionRequest() {
        }
        
        public UpdateBreakSessionRequest(StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBreakSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double hours;
        
        public UpdateBreakSessionRequestBody() {
        }
        
        public UpdateBreakSessionRequestBody(string userName, int sessionId, System.DateTime date, double hours) {
            this.userName = userName;
            this.sessionId = sessionId;
            this.date = date;
            this.hours = hours;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBreakSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBreakSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionResponseBody Body;
        
        public UpdateBreakSessionResponse() {
        }
        
        public UpdateBreakSessionResponse(StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBreakSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateBreakSessionResult;
        
        public UpdateBreakSessionResponseBody() {
        }
        
        public UpdateBreakSessionResponseBody(string UpdateBreakSessionResult) {
            this.UpdateBreakSessionResult = UpdateBreakSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBreakSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBreakSession", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequestBody Body;
        
        public DeleteBreakSessionRequest() {
        }
        
        public DeleteBreakSessionRequest(StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBreakSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sessionId;
        
        public DeleteBreakSessionRequestBody() {
        }
        
        public DeleteBreakSessionRequestBody(string userName, int sessionId) {
            this.userName = userName;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBreakSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBreakSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionResponseBody Body;
        
        public DeleteBreakSessionResponse() {
        }
        
        public DeleteBreakSessionResponse(StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBreakSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteBreakSessionResult;
        
        public DeleteBreakSessionResponseBody() {
        }
        
        public DeleteBreakSessionResponseBody(string DeleteBreakSessionResult) {
            this.DeleteBreakSessionResult = DeleteBreakSessionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BreakSessionSoapChannel : StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BreakSessionSoapClient : System.ServiceModel.ClientBase<StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap>, StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap {
        
        public BreakSessionSoapClient() {
        }
        
        public BreakSessionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BreakSessionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BreakSessionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BreakSessionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsResponse StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.GetBreakSessions(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequest request) {
            return base.Channel.GetBreakSessions(request);
        }
        
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionModel[] GetBreakSessions(string userName) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequestBody();
            inValue.Body.userName = userName;
            StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsResponse retVal = ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).GetBreakSessions(inValue);
            return retVal.Body.GetBreakSessionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsResponse> StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.GetBreakSessionsAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequest request) {
            return base.Channel.GetBreakSessionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsResponse> GetBreakSessionsAsync(string userName) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionsRequestBody();
            inValue.Body.userName = userName;
            return ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).GetBreakSessionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdResponse StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.GetBreakSessionById(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequest request) {
            return base.Channel.GetBreakSessionById(request);
        }
        
        public StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionModel GetBreakSessionById(string userName, int sessionId) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdResponse retVal = ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).GetBreakSessionById(inValue);
            return retVal.Body.GetBreakSessionByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdResponse> StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.GetBreakSessionByIdAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequest request) {
            return base.Channel.GetBreakSessionByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdResponse> GetBreakSessionByIdAsync(string userName, int sessionId) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.GetBreakSessionByIdRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            return ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).GetBreakSessionByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionResponse StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.AddBreakSession(StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequest request) {
            return base.Channel.AddBreakSession(request);
        }
        
        public string AddBreakSession(string userName, System.DateTime date, double hours) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.date = date;
            inValue.Body.hours = hours;
            StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionResponse retVal = ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).AddBreakSession(inValue);
            return retVal.Body.AddBreakSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionResponse> StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.AddBreakSessionAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequest request) {
            return base.Channel.AddBreakSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionResponse> AddBreakSessionAsync(string userName, System.DateTime date, double hours) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.AddBreakSessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.date = date;
            inValue.Body.hours = hours;
            return ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).AddBreakSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionResponse StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.UpdateBreakSession(StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequest request) {
            return base.Channel.UpdateBreakSession(request);
        }
        
        public string UpdateBreakSession(string userName, int sessionId, System.DateTime date, double hours) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            inValue.Body.date = date;
            inValue.Body.hours = hours;
            StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionResponse retVal = ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).UpdateBreakSession(inValue);
            return retVal.Body.UpdateBreakSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionResponse> StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.UpdateBreakSessionAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequest request) {
            return base.Channel.UpdateBreakSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionResponse> UpdateBreakSessionAsync(string userName, int sessionId, System.DateTime date, double hours) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.UpdateBreakSessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            inValue.Body.date = date;
            inValue.Body.hours = hours;
            return ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).UpdateBreakSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionResponse StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.DeleteBreakSession(StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequest request) {
            return base.Channel.DeleteBreakSession(request);
        }
        
        public string DeleteBreakSession(string userName, int sessionId) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionResponse retVal = ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).DeleteBreakSession(inValue);
            return retVal.Body.DeleteBreakSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionResponse> StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap.DeleteBreakSessionAsync(StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequest request) {
            return base.Channel.DeleteBreakSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionResponse> DeleteBreakSessionAsync(string userName, int sessionId) {
            StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequest inValue = new StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequest();
            inValue.Body = new StudentsPerformancePredictionTool_CW1.BreakSessionService.DeleteBreakSessionRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.sessionId = sessionId;
            return ((StudentsPerformancePredictionTool_CW1.BreakSessionService.BreakSessionSoap)(this)).DeleteBreakSessionAsync(inValue);
        }
    }
}
